/* The following code was generated by JFlex 1.4.3 on 11.10.15 2:00 */

package ru.spbau.kozlov.queries.lexer;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static ru.spbau.kozlov.queries.parsing.QueryLanguageElementTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11.10.15 2:00 from the specification file
 * <tt>/Users/adkozlov/Documents/git-au/scala-2015/query-language/src/ru/spbau/kozlov/queries/lexer/_QueryLanguageLexer.flex</tt>
 */
public class _QueryLanguageLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\1\1\1\1\1\1\1\22\0\1\1\1\45\1\12"+
    "\1\0\1\51\1\37\2\0\1\46\1\47\1\13\1\34\1\0\1\35"+
    "\1\4\1\36\1\3\11\2\1\14\6\0\1\54\3\5\1\57\3\5"+
    "\1\60\1\5\1\61\3\5\1\6\2\5\1\7\1\55\1\56\6\5"+
    "\3\0\1\40\1\5\1\0\1\17\1\41\1\30\1\25\1\16\1\26"+
    "\1\42\1\21\1\23\1\5\1\50\1\32\1\24\1\27\1\33\1\44"+
    "\1\5\1\22\1\31\1\20\1\53\1\5\1\15\1\43\2\5\1\0"+
    "\1\10\1\0\1\11\u202d\0\1\52\udf53\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\2\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\5\1\13\2\5\1\14"+
    "\1\15\4\5\1\16\1\17\1\20\1\21\1\22\2\5"+
    "\1\23\1\24\1\25\1\5\1\26\1\27\1\5\1\4"+
    "\1\30\1\31\1\32\10\5\1\33\6\5\1\34\1\5"+
    "\1\35\1\5\1\36\1\37\2\5\1\40\2\5\1\41"+
    "\1\42\3\5\1\43\3\5\1\44\1\45\1\46\3\5"+
    "\1\47\4\5\1\50\1\51\15\5\1\52\2\5\1\53"+
    "\1\54\1\55\1\5\1\56\1\57\1\60\1\5\1\61"+
    "\3\5\1\62\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\u015e"+
    "\0\62\0\62\0\62\0\u0190\0\62\0\u01c2\0\u01f4\0\u0226"+
    "\0\u0258\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\62"+
    "\0\62\0\62\0\62\0\62\0\u03b6\0\u03e8\0\62\0\62"+
    "\0\62\0\u041a\0\62\0\62\0\u044c\0\u047e\0\62\0\u012c"+
    "\0\62\0\u04b0\0\u04e2\0\u0514\0\u0546\0\u0578\0\u05aa\0\u05dc"+
    "\0\u060e\0\u0640\0\u0672\0\u06a4\0\u06d6\0\u0708\0\u073a\0\u076c"+
    "\0\u012c\0\u079e\0\u012c\0\u07d0\0\u012c\0\u012c\0\u0802\0\u0834"+
    "\0\u012c\0\u0866\0\u0898\0\u012c\0\u012c\0\u08ca\0\u08fc\0\u092e"+
    "\0\u012c\0\u0960\0\u0992\0\u09c4\0\u012c\0\u012c\0\u012c\0\u09f6"+
    "\0\u0a28\0\u0a5a\0\u012c\0\u0a8c\0\u0abe\0\u0af0\0\u0b22\0\u012c"+
    "\0\u012c\0\u0b54\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\u0c80"+
    "\0\u0cb2\0\u0ce4\0\u0d16\0\u0d48\0\u0d7a\0\u0dac\0\u012c\0\u0dde"+
    "\0\u0e10\0\u012c\0\u012c\0\u012c\0\u0e42\0\u012c\0\u012c\0\u012c"+
    "\0\u0e74\0\u012c\0\u0ea6\0\u0ed8\0\u0f0a\0\u012c\0\u012c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\7"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\2\7\1\22\1\23\1\24\2\7\1\25\1\26"+
    "\1\27\1\7\1\30\1\31\1\32\1\33\1\34\1\7"+
    "\1\35\1\7\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\7\1\45\5\7\63\0\1\3\62\0\2\4"+
    "\1\46\3\7\5\0\17\7\5\0\4\7\3\0\1\7"+
    "\2\0\7\7\2\0\2\7\1\46\3\7\5\0\17\7"+
    "\5\0\4\7\3\0\1\7\2\0\7\7\4\0\1\47"+
    "\57\0\2\7\1\0\3\7\5\0\17\7\5\0\4\7"+
    "\3\0\1\7\2\0\7\7\2\0\2\7\1\0\2\7"+
    "\1\50\5\0\17\7\5\0\4\7\3\0\1\7\2\0"+
    "\7\7\13\0\1\51\50\0\2\7\1\0\3\7\5\0"+
    "\1\7\1\52\15\7\5\0\4\7\3\0\1\7\2\0"+
    "\7\7\2\0\2\7\1\0\3\7\5\0\17\7\5\0"+
    "\2\7\1\53\1\7\3\0\1\7\2\0\1\54\6\7"+
    "\2\0\2\7\1\0\3\7\5\0\5\7\1\55\11\7"+
    "\5\0\1\56\3\7\3\0\1\7\2\0\7\7\2\0"+
    "\2\7\1\0\3\7\5\0\2\7\1\57\2\7\1\60"+
    "\1\61\10\7\5\0\4\7\3\0\1\7\2\0\7\7"+
    "\2\0\2\7\1\0\3\7\5\0\12\7\1\62\4\7"+
    "\5\0\4\7\3\0\1\7\2\0\7\7\2\0\2\7"+
    "\1\0\3\7\5\0\16\7\1\63\5\0\4\7\3\0"+
    "\1\7\2\0\7\7\2\0\2\7\1\0\3\7\5\0"+
    "\1\7\1\64\14\7\1\65\5\0\4\7\3\0\1\7"+
    "\2\0\7\7\2\0\2\7\1\0\3\7\5\0\2\7"+
    "\1\66\13\7\1\67\5\0\4\7\3\0\1\7\2\0"+
    "\7\7\2\0\2\7\1\0\3\7\5\0\6\7\1\70"+
    "\10\7\5\0\4\7\3\0\1\7\2\0\7\7\2\0"+
    "\2\7\1\0\3\7\5\0\12\7\1\71\3\7\1\72"+
    "\5\0\1\7\1\73\2\7\3\0\1\7\2\0\7\7"+
    "\2\0\2\7\1\0\3\7\5\0\2\7\1\74\14\7"+
    "\5\0\4\7\3\0\1\7\2\0\7\7\2\0\2\7"+
    "\1\0\3\7\5\0\6\7\1\75\10\7\5\0\4\7"+
    "\3\0\1\7\2\0\7\7\2\0\2\7\1\0\3\7"+
    "\5\0\7\7\1\76\7\7\5\0\4\7\3\0\1\7"+
    "\2\0\7\7\2\0\2\7\1\0\3\7\5\0\17\7"+
    "\5\0\4\7\3\0\1\7\2\0\2\7\1\77\4\7"+
    "\2\0\2\46\60\0\2\7\1\0\3\7\5\0\2\7"+
    "\1\100\14\7\5\0\4\7\3\0\1\7\2\0\7\7"+
    "\2\0\2\7\1\0\3\7\5\0\17\7\5\0\3\7"+
    "\1\101\3\0\1\7\2\0\7\7\2\0\2\7\1\0"+
    "\3\7\5\0\5\7\1\102\11\7\5\0\4\7\3\0"+
    "\1\7\2\0\7\7\2\0\2\7\1\0\3\7\5\0"+
    "\13\7\1\103\3\7\5\0\4\7\3\0\1\7\2\0"+
    "\7\7\2\0\2\7\1\0\3\7\5\0\14\7\1\104"+
    "\2\7\5\0\4\7\3\0\1\7\2\0\7\7\2\0"+
    "\2\7\1\0\3\7\5\0\12\7\1\105\4\7\5\0"+
    "\4\7\3\0\1\7\2\0\7\7\2\0\2\7\1\0"+
    "\3\7\5\0\2\7\1\106\14\7\5\0\4\7\3\0"+
    "\1\7\2\0\7\7\2\0\2\7\1\0\3\7\5\0"+
    "\7\7\1\107\7\7\5\0\4\7\3\0\1\7\2\0"+
    "\7\7\2\0\2\7\1\0\3\7\5\0\3\7\1\110"+
    "\13\7\5\0\4\7\3\0\1\7\2\0\7\7\2\0"+
    "\2\7\1\0\3\7\5\0\10\7\1\111\6\7\5\0"+
    "\4\7\3\0\1\7\2\0\7\7\2\0\2\7\1\0"+
    "\3\7\5\0\11\7\1\112\5\7\5\0\4\7\3\0"+
    "\1\7\2\0\7\7\2\0\2\7\1\0\3\7\5\0"+
    "\15\7\1\113\1\7\5\0\4\7\3\0\1\7\2\0"+
    "\7\7\2\0\2\7\1\0\3\7\5\0\13\7\1\114"+
    "\3\7\5\0\4\7\3\0\1\7\2\0\7\7\2\0"+
    "\2\7\1\0\3\7\5\0\14\7\1\115\2\7\5\0"+
    "\4\7\3\0\1\7\2\0\7\7\2\0\2\7\1\0"+
    "\3\7\5\0\12\7\1\116\4\7\5\0\4\7\3\0"+
    "\1\7\2\0\7\7\2\0\2\7\1\0\3\7\5\0"+
    "\17\7\5\0\1\7\1\117\2\7\3\0\1\7\2\0"+
    "\7\7\2\0\2\7\1\0\3\7\5\0\7\7\1\120"+
    "\7\7\5\0\4\7\3\0\1\7\2\0\7\7\2\0"+
    "\2\7\1\0\3\7\5\0\17\7\5\0\4\7\3\0"+
    "\1\7\2\0\3\7\1\121\3\7\2\0\2\7\1\0"+
    "\3\7\5\0\3\7\1\122\13\7\5\0\4\7\3\0"+
    "\1\7\2\0\7\7\2\0\2\7\1\0\3\7\5\0"+
    "\16\7\1\123\5\0\4\7\3\0\1\7\2\0\7\7"+
    "\2\0\2\7\1\0\3\7\5\0\3\7\1\124\7\7"+
    "\1\125\1\126\2\7\5\0\4\7\3\0\1\7\2\0"+
    "\7\7\2\0\2\7\1\0\3\7\5\0\12\7\1\127"+
    "\4\7\5\0\4\7\3\0\1\7\2\0\7\7\2\0"+
    "\2\7\1\0\3\7\5\0\1\7\1\130\15\7\5\0"+
    "\4\7\3\0\1\7\2\0\7\7\2\0\2\7\1\0"+
    "\3\7\5\0\16\7\1\131\5\0\4\7\3\0\1\7"+
    "\2\0\7\7\2\0\2\7\1\0\3\7\5\0\6\7"+
    "\1\132\10\7\5\0\4\7\3\0\1\7\2\0\7\7"+
    "\2\0\2\7\1\0\3\7\5\0\15\7\1\133\1\7"+
    "\5\0\4\7\3\0\1\7\2\0\7\7\2\0\2\7"+
    "\1\0\3\7\5\0\4\7\1\134\12\7\5\0\4\7"+
    "\3\0\1\7\2\0\7\7\2\0\2\7\1\0\3\7"+
    "\5\0\7\7\1\135\7\7\5\0\4\7\3\0\1\7"+
    "\2\0\7\7\2\0\2\7\1\0\3\7\5\0\17\7"+
    "\5\0\4\7\3\0\1\7\2\0\4\7\1\136\2\7"+
    "\2\0\2\7\1\0\3\7\5\0\4\7\1\137\12\7"+
    "\5\0\4\7\3\0\1\7\2\0\7\7\2\0\2\7"+
    "\1\0\3\7\5\0\2\7\1\140\14\7\5\0\4\7"+
    "\3\0\1\7\2\0\7\7\2\0\2\7\1\0\3\7"+
    "\5\0\16\7\1\141\5\0\4\7\3\0\1\7\2\0"+
    "\7\7\2\0\2\7\1\0\3\7\5\0\6\7\1\142"+
    "\10\7\5\0\4\7\3\0\1\7\2\0\7\7\2\0"+
    "\2\7\1\0\3\7\5\0\14\7\1\143\2\7\5\0"+
    "\4\7\3\0\1\7\2\0\7\7\2\0\2\7\1\0"+
    "\3\7\5\0\12\7\1\144\4\7\5\0\4\7\3\0"+
    "\1\7\2\0\7\7\2\0\2\7\1\0\3\7\5\0"+
    "\2\7\1\145\14\7\5\0\4\7\3\0\1\7\2\0"+
    "\7\7\2\0\2\7\1\0\3\7\5\0\1\7\1\146"+
    "\15\7\5\0\4\7\3\0\1\7\2\0\7\7\2\0"+
    "\2\7\1\0\3\7\5\0\2\7\1\147\14\7\5\0"+
    "\4\7\3\0\1\7\2\0\7\7\2\0\2\7\1\0"+
    "\2\7\1\150\5\0\17\7\5\0\4\7\3\0\1\7"+
    "\2\0\7\7\2\0\2\7\1\0\3\7\5\0\1\7"+
    "\1\151\15\7\5\0\4\7\3\0\1\7\2\0\7\7"+
    "\2\0\2\7\1\0\3\7\5\0\12\7\1\152\4\7"+
    "\5\0\4\7\3\0\1\7\2\0\7\7\2\0\2\7"+
    "\1\0\3\7\5\0\14\7\1\153\2\7\5\0\4\7"+
    "\3\0\1\7\2\0\7\7\2\0\2\7\1\0\3\7"+
    "\5\0\12\7\1\154\4\7\5\0\4\7\3\0\1\7"+
    "\2\0\7\7\2\0\2\7\1\0\3\7\5\0\15\7"+
    "\1\155\1\7\5\0\4\7\3\0\1\7\2\0\7\7"+
    "\2\0\2\7\1\0\3\7\5\0\1\7\1\156\15\7"+
    "\5\0\4\7\3\0\1\7\2\0\7\7\2\0\2\7"+
    "\1\0\3\7\5\0\5\7\1\157\11\7\5\0\4\7"+
    "\3\0\1\7\2\0\7\7\2\0\2\7\1\0\3\7"+
    "\5\0\10\7\1\160\6\7\5\0\4\7\3\0\1\7"+
    "\2\0\7\7\2\0\2\7\1\0\3\7\5\0\17\7"+
    "\5\0\4\7\3\0\1\7\2\0\5\7\1\161\1\7"+
    "\2\0\2\7\1\0\3\7\5\0\5\7\1\162\11\7"+
    "\5\0\4\7\3\0\1\7\2\0\7\7\2\0\2\7"+
    "\1\0\3\7\5\0\2\7\1\163\14\7\5\0\4\7"+
    "\3\0\1\7\2\0\7\7\2\0\2\7\1\0\3\7"+
    "\5\0\17\7\5\0\4\7\3\0\1\7\2\0\2\7"+
    "\1\164\4\7\2\0\2\7\1\0\3\7\5\0\3\7"+
    "\1\165\13\7\5\0\4\7\3\0\1\7\2\0\7\7"+
    "\2\0\2\7\1\0\3\7\5\0\17\7\5\0\4\7"+
    "\3\0\1\7\2\0\6\7\1\166\2\0\2\7\1\0"+
    "\3\7\5\0\1\7\1\167\15\7\5\0\4\7\3\0"+
    "\1\7\2\0\7\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3900];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\3\11\1\1\1\11\12\1\5\11"+
    "\2\1\3\11\1\1\2\11\2\1\1\11\1\1\1\11"+
    "\116\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public _QueryLanguageLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _QueryLanguageLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 152) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 30: 
          { return QUERY_LANGUAGE_PI;
          }
        case 52: break;
        case 24: 
          { return QUERY_LANGUAGE_RANGE;
          }
        case 53: break;
        case 45: 
          { return QUERY_LANGUAGE_ARCSIN;
          }
        case 54: break;
        case 4: 
          { return QUERY_LANGUAGE_FLOAT;
          }
        case 55: break;
        case 17: 
          { return QUERY_LANGUAGE_MODULO_OPERATOR_1;
          }
        case 56: break;
        case 40: 
          { return QUERY_LANGUAGE_TIME_KEYWORD;
          }
        case 57: break;
        case 51: 
          { return QUERY_LANGUAGE_TRANSLATE_KEYWORD;
          }
        case 58: break;
        case 11: 
          { return QUERY_LANGUAGE_E;
          }
        case 59: break;
        case 16: 
          { return QUERY_LANGUAGE_DIVISION_OPERATOR;
          }
        case 60: break;
        case 44: 
          { return QUERY_LANGUAGE_ARCCOS;
          }
        case 61: break;
        case 23: 
          { return QUERY_LANGUAGE_EURO_SIGN;
          }
        case 62: break;
        case 29: 
          { return QUERY_LANGUAGE_LG;
          }
        case 63: break;
        case 41: 
          { return QUERY_LANGUAGE_INTO_KEYWORD;
          }
        case 64: break;
        case 38: 
          { return QUERY_LANGUAGE_LOG;
          }
        case 65: break;
        case 39: 
          { return QUERY_LANGUAGE_EURO;
          }
        case 66: break;
        case 33: 
          { return QUERY_LANGUAGE_ABS;
          }
        case 67: break;
        case 6: 
          { return QUERY_LANGUAGE_OR_OPERATOR_2;
          }
        case 68: break;
        case 27: 
          { return QUERY_LANGUAGE_IN_KEYWORD;
          }
        case 69: break;
        case 26: 
          { return QUERY_LANGUAGE_INVOLUTION_OPERATOR_2;
          }
        case 70: break;
        case 14: 
          { return QUERY_LANGUAGE_ADDITION_OPERATOR;
          }
        case 71: break;
        case 21: 
          { return QUERY_LANGUAGE_RIGHT_PAREN;
          }
        case 72: break;
        case 32: 
          { return QUERY_LANGUAGE_EXP;
          }
        case 73: break;
        case 43: 
          { return QUERY_LANGUAGE_ARCTAN;
          }
        case 74: break;
        case 50: 
          { return QUERY_LANGUAGE_ASTERISK;
          }
        case 75: break;
        case 7: 
          { return QUERY_LANGUAGE_TILDE;
          }
        case 76: break;
        case 5: 
          { return QUERY_LANGUAGE_WORD;
          }
        case 77: break;
        case 48: 
          { return QUERY_LANGUAGE_CACHED_KEYWORD;
          }
        case 78: break;
        case 37: 
          { return QUERY_LANGUAGE_SIN;
          }
        case 79: break;
        case 31: 
          { return QUERY_LANGUAGE_KILOMETRE;
          }
        case 80: break;
        case 22: 
          { return QUERY_LANGUAGE_DOLLAR_SIGN;
          }
        case 81: break;
        case 13: 
          { return QUERY_LANGUAGE_METRE;
          }
        case 82: break;
        case 42: 
          { return QUERY_LANGUAGE_GAMMA;
          }
        case 83: break;
        case 36: 
          { return QUERY_LANGUAGE_COS;
          }
        case 84: break;
        case 25: 
          { return QUERY_LANGUAGE_OR_OPERATOR_1;
          }
        case 85: break;
        case 18: 
          { return QUERY_LANGUAGE_INVOLUTION_OPERATOR_1;
          }
        case 86: break;
        case 3: 
          { return QUERY_LANGUAGE_INTEGER;
          }
        case 87: break;
        case 9: 
          { return QUERY_LANGUAGE_MULTIPLICATION_OPERATOR;
          }
        case 88: break;
        case 20: 
          { return QUERY_LANGUAGE_LEFT_PAREN;
          }
        case 89: break;
        case 35: 
          { return QUERY_LANGUAGE_MODULO_OPERATOR_2;
          }
        case 90: break;
        case 47: 
          { return QUERY_LANGUAGE_DOLLAR;
          }
        case 91: break;
        case 10: 
          { return QUERY_LANGUAGE_COLON;
          }
        case 92: break;
        case 46: 
          { return QUERY_LANGUAGE_DEFINE_KEYWORD;
          }
        case 93: break;
        case 12: 
          { return QUERY_LANGUAGE_I;
          }
        case 94: break;
        case 34: 
          { return QUERY_LANGUAGE_TAN;
          }
        case 95: break;
        case 8: 
          { return QUERY_LANGUAGE_QUOTATION_MARK;
          }
        case 96: break;
        case 49: 
          { return QUERY_LANGUAGE_WEATHER_KEYWORD;
          }
        case 97: break;
        case 2: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 98: break;
        case 28: 
          { return QUERY_LANGUAGE_LN;
          }
        case 99: break;
        case 15: 
          { return QUERY_LANGUAGE_SUBSTRACTION_OPERATOR;
          }
        case 100: break;
        case 1: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 101: break;
        case 19: 
          { return QUERY_LANGUAGE_FACTORIAL;
          }
        case 102: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
